services:
  db:
    image: mysql:8.4
    container_name: daver_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-pizzatime}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-daver_db}
      MYSQL_USER: ${MYSQL_USER:-daver}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pizzatime}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  ollama:
    image: ollama/ollama:latest
    container_name: daver_ollama
    restart: unless-stopped

    # Expose default Ollama REST API port
    ports:
      - "11434:11434"

    # Persist downloaded models & metadata here
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama_entrypoint.sh:/entrypoint.sh
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

volumes:
  db_data:
    name: daver_db_data
  ollama_data:
    name: daver_ollama_data
